# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# add two jobs to print hello world statement
jobs:
  # First job to print hello
  # print_hello:
  #   docker:
  #     - image: circleci/node:13.8.0
    
  #   steps:
  #     - run: echo Hello

  # Second Job to print world
  # print_world:
  #   docker:
  #     - image: circleci/node:13.8.0
    
  #   steps:
  #     - run: echo world!
  
  # Thrid Job to test environment variables
  # test_env_vars:
  #   docker:
  #     - image: cimg/base:2020.01
    
  #   steps:
  #     - run:
  #         name: "echo name using environment variable"
  #         command: |
  #           echo $NAME

  # Fourth Job to save the output to file
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    
    steps:
      - run: echo "Hello World!" > ~/output.txt
      
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01

    steps:
      - attach_workspace:
          at: ~/output.txt
      
      - run: cat ~/output.txt

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
        requires:
          - save_hello_world_output
      # - print_hello
      # - print_world:
          # requires:
            # - print_hello
      # - test_env_vars