# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  image_build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker image
          command: |
            docker build --tag=rab7a:${CIRCLE_BUILD_NUM} .
            docker images ls
      - run:
          name: push to dockerhub
          command: |
            dockerpath="fadykhallaf/rab7a:${CIRCLE_BUILD_NUM}"
            docker tag rab7a:${CIRCLE_BUILD_NUM} $dockerpath
            echo "Docker ID and Image: $dockerpath"
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker image push $dockerpath
            
          
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - image_build